### ISSUE TITLE
NAWS sub-negotiation is not handled when a width our height is 255.

### ISSUE THREAD

**Issue by joshuah** [wez/telnetjs#1]
Clients which properly escape their NAWS sub negotiation will show incorrect window sizes if the width or height is 255 characters.

As required by the Telnet protocol, any occurrence of 255 in the
   subnegotiation must be doubled to distinguish it from the IAC
   character (which has a value of 255).

Putty:
Buffer 00 fe 00 19
window size is 254 x 25
Buffer 00 ff ff 00 19     <-  The value of 255 is escaped.
window size is 255 x -256

WinTin++
Buffer 00 e6 00 16
window size is 230 x 22
Buffer 00 ff 00 16  <- The value 255 was not properly escaped?
window size is 255 x 22

**Comment by wez** [comment]
I've pushed https://github.com/wez/telnetjs/commit/09b5e2ddbe699b76062daa1b0dbf5fdf67346f69 which works for me; can you confirm the fix?

**Comment by joshuah** [comment]
Works. :)
